name: Create Release Pull Request

on:
 workflow_dispatch:
    inputs:
      jira_ticket_number:
        description: JIRA Ticket number for the release
        required: true
      version_tobe_released:
        description: Version number to be released
        required: true
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: deb1990/release-pr-github-action@1.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_NAME: 2.10.0
          IS_CIVICRM_EXTENTION: true
          FILE_UPDATE_COMMIT_DESC: "${{ github.event.inputs.jira_ticket_number }}: Update info.xml"
          RELEASE_PR_TITLE: "${{ github.event.inputs.jira_ticket_number }}: Release v${{ github.event.inputs.version_tobe_released }}"
          RELEASE_PR_IDENTIFIER_LABEL: release
